# Generated by Django 3.1.3 on 2020-12-17 13:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='motherboard',
            name='AvailabilityOfM2',
            field=models.BooleanField(null=True),
        ),
        migrations.AlterField(
            model_name='motherboard',
            name='MaximumSupportedMemoryFrequency',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='motherboard',
            name='Socket',
            field=models.CharField(max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='motherboard',
            name='TypeOfSupportedMemory',
            field=models.CharField(max_length=10, null=True),
        ),
    ]
