# Generated by Django 3.1.3 on 2020-12-17 14:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_auto_20201217_2035'),
    ]

    operations = [
        migrations.AddField(
            model_name='cpu',
            name='Title',
            field=models.CharField(default='', max_length=20),
        ),
        migrations.AddField(
            model_name='gpu',
            name='Title',
            field=models.CharField(default='', max_length=20),
        ),
        migrations.AddField(
            model_name='motherboard',
            name='Title',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='ram',
            name='Title',
            field=models.CharField(default='', max_length=20),
        ),
        migrations.AddField(
            model_name='storage',
            name='Title',
            field=models.CharField(default='', max_length=20),
        ),
        migrations.AlterField(
            model_name='gpu',
            name='ChipFfrequency',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='gpu',
            name='MemoryCapacity',
            field=models.IntegerField(),
        ),
    ]
