# Generated by Django 3.1.3 on 2020-12-17 14:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_auto_20201217_2102'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ram',
            name='Volume',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='storage',
            name='ReadingSpeed',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='storage',
            name='RecordingSpeed',
            field=models.IntegerField(),
        ),
    ]
