# Generated by Django 3.1.3 on 2020-12-18 03:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_auto_20201218_1022'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cpu',
            name='TechnologicalProcess',
            field=models.IntegerField(),
        ),
    ]
